# This is a basic workflow to help you get started with Actions

name: first

# Controls when the workflow will run
on: 

  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
jobs:
  run-shell-command:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo multiline1,
          echo multiline2.
          
      - name: Run a multi-line script
        run: |
          node -v
          npm -v
